"""HTML das ferramentas locais; regras e limitações têm fonte documental."""
def field(name, label, value='', positive=False):
    minimum = '0.01' if positive else '0'
    return f'<div><label for="{name}">{label}</label><input id="{name}" name="{name}" type="number" min="{minimum}" step="any" value="{value}" required></div>'

def tools_html():
    return '''<section class="page-intro"><h1>Ferramentas de aplicação</h1><p class="lead">Confira premissas financeiras e experimente a contagem de trabalho iniciado. As contas e o quadro funcionam localmente, sem enviar dados a um serviço.</p></section>
<nav class="topic-nav" aria-label="Ferramentas"><a href="#retorno">Retorno</a><a href="#capacidade">Capacidade</a><a href="#divida">Dívida</a><a href="#fluxo">Fluxo</a></nav>
<div class="tools-layout"><section id="retorno" class="tool-section"><h2>Retorno de uma melhoria</h2><p>Horizonte de 12 meses. Benefício e custo mensal constantes, na mesma moeda. A estimativa não é resultado observado.</p>
<form id="roi-form" class="tool-form">'''+field('investment','Investimento inicial (R$)','9000',True)+field('benefit','Benefício bruto mensal (R$)','3000')+field('recurring','Custo recorrente mensal (R$)','500')+'''<button type="submit">Calcular retorno</button></form><div id="roi-result" class="tool-result" role="status" aria-live="polite">Preencha as premissas e calcule.</div><p>ROI líquido anual: <code>((benefício − custo mensal) × 12 − investimento) / investimento × 100</code>. Payback simples considera benefício líquido mensal positivo.</p><p><a href="docs/indicadores/financeiros.html">Definições, exemplo e limites financeiros</a></p></section>
<section id="capacidade" class="tool-section"><h2>Valor atribuído ao tempo</h2><p>Horas liberadas representam capacidade potencial. Só trate o valor como redução de despesa quando houver alteração efetiva de gasto. Não some esse valor ao benefício de retorno sem conferir duplicidade.</p><form id="capacity-form" class="tool-form">'''+field('hours','Horas liberadas por pessoa/mês')+field('people','Pessoas afetadas')+field('hourly','Custo estimado por hora (R$)')+'''<button type="submit">Estimar capacidade</button></form><div id="capacity-result" class="tool-result" role="status" aria-live="polite">Informe as premissas de tempo.</div></section>
<section id="divida" class="tool-section"><h2>DAN financeiro local</h2><p>Razão entre custo estimado de refatoração e orçamento anual de TI. Informe escopo, data e incerteza na sua memória de cálculo. A razão não determina risco de parada ou uma faixa de segurança.</p><form id="dan-form" class="tool-form">'''+field('debt-hours','Esforço estimado de refatoração (horas)')+field('debt-hourly','Custo estimado por hora (R$)')+field('budget','Orçamento anual de TI (R$)','',True)+'''<button type="submit">Calcular a razão</button></form><div id="dan-result" class="tool-result" role="status" aria-live="polite">Informe esforço, custo e orçamento.</div><p><a href="docs/indicadores/financeiros.html">Diferença entre DAN financeiro e proporção de itens legados</a></p></section></div>
<section id="fluxo" class="tool-section"><h2>Contagem de trabalho iniciado</h2><p>Quadro de exercício. Até três itens iniciados por executor como parâmetro inicial, incluindo testes e bloqueios. Uma emergência pode exigir exceção registrada na operação; este exercício mantém o limite para mostrar sua contagem.</p><p>Use nomes de exercício. Os cartões permanecem somente nesta página e são descartados ao recarregar.</p><form id="board-form" class="tool-form"><div><label for="task-title">Demanda</label><input id="task-title" maxlength="160" required></div><div><label for="executor">Executor</label><input id="executor" maxlength="80" required></div><button type="submit">Adicionar à fila</button></form><p id="board-status" role="status" aria-live="polite">A fila começa vazia.</p><div id="board" class="board"></div><button type="button" id="board-reset">Limpar exercício</button><p><a href="docs/nucleo/execucao-servicos.html">Estados, suspensão e emergência</a> · <a href="docs/guias/priorizar-demandas.html">Priorizar demandas</a></p></section><noscript>As ferramentas precisam de JavaScript. As fórmulas e os guias continuam disponíveis nos links.</noscript>'''
